version: '3.4'

services:
  vacationsmodule.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__VacationsModuleDB=Server=vacationsmodule.sqldb;Database=ReservationsDB;User=sa;Password=Sarandompassword1;TrustServerCertificate=true
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  vacationsmodule.sqldb:
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD : "Sarandompassword1"
      ACCEPT_EULA: "Y"
